### ISSUE TITLE
Unable to install in python 3.11

### ISSUE THREAD

**Issue by irleader** [bittremieux/spectrum_utils#44]
When install in python 3.11, the following error occurs:

```
Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-glfat_q4/numba_5afd43df9d974845953722af212a915c/setup.py", line 51, in <module>
          _guard_py_ver()
        File "/tmp/pip-install-glfat_q4/numba_5afd43df9d974845953722af212a915c/setup.py", line 48, in _guard_py_ver
          raise RuntimeError(msg.format(cur_py, min_py, max_py))
      RuntimeError: Cannot install on Python version 3.11.0; only versions >=3.7,<3.11 are supported.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

Is it possible to modify the setup file to allow installation? Thanks.

**Comment by bittremieux** [comment]
Thanks for reporting the issue. The problem lies with Numba, which should [support Python 3.11 very soon, however](https://github.com/numba/numba/issues/8304). I am currently attending a conference and will have time to properly test installing with restricted Numba versions next week.

In the mean time, if this is a pressing matter, using Python 3.10 should be a quick fix.
